'use client';

import { useEffect, useState } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter, useParams } from 'next/navigation';
import Image from 'next/image';
import QRCode from 'qrcode';
import Header from '@/components/Header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { ArrowLeft, Download, Calendar, Clock, MapPin, Ticket, Loader2 } from 'lucide-react';
import { ITicket } from '@/models/Ticket';

interface TicketWithEvent extends ITicket {
  eventId: {
    _id: string;
    name: string;
    date: Date;
    time: string;
    location: {
      name: string;
      address: string;
    };
    image: string;
    organizer: string;
  };
}

export default function TicketPage() {
  const { data: session } = useSession();
  const router = useRouter();
  const params = useParams();
  const [ticket, setTicket] = useState<TicketWithEvent | null>(null);
  const [loading, setLoading] = useState(true);
  const [qrCodeUrl, setQrCodeUrl] = useState<string>('');

  useEffect(() => {
    if (!session) {
      router.push('/auth/signin');
      return;
    }
    fetchTicket();
  }, [session, params.id]);

  const fetchTicket = async () => {
    try {
      const response = await fetch(`/api/tickets/${params.id}`);
      if (response.ok) {
        const ticketData = await response.json();
        setTicket(ticketData);
        
        // Generate QR code
        if (ticketData.qrCode) {
          const qrUrl = await QRCode.toDataURL(ticketData.qrCode, {
            width: 200,
            margin: 2,
            color: {
              dark: '#000000',
              light: '#FFFFFF',
            },
          });
          setQrCodeUrl(qrUrl);
        }
      } else {
        router.push('/my-tickets');
      }
    } catch (error) {
      console.error('Error fetching ticket:', error);
      router.push('/my-tickets');
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (date: Date) => {
    return new Date(date).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  const formatPrice = (price: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
    }).format(price);
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active':
        return 'bg-green-100 text-green-800';
      case 'scanned':
        return 'bg-blue-100 text-blue-800';
      case 'cancelled':
        return 'bg-red-100 text-red-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const handleDownload = () => {
    if (!ticket) return;
    
    // Create a printable version of the ticket
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Ticket - ${ticket.eventId.name}</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              .ticket { border: 2px solid #000; padding: 20px; max-width: 400px; }
              .header { text-align: center; margin-bottom: 20px; }
              .qr-code { text-align: center; margin: 20px 0; }
              .details { margin: 10px 0; }
              .footer { text-align: center; margin-top: 20px; font-size: 12px; }
            </style>
          </head>
          <body>
            <div class="ticket">
              <div class="header">
                <h1>TICKETr</h1>
                <h2>${ticket.eventId.name}</h2>
              </div>
              <div class="qr-code">
                <img src="${qrCodeUrl}" alt="QR Code" />
              </div>
              <div class="details">
                <p><strong>Ticket ID:</strong> ${ticket.ticketId}</p>
                <p><strong>Date:</strong> ${formatDate(ticket.eventId.date)}</p>
                <p><strong>Time:</strong> ${ticket.eventId.time}</p>
                <p><strong>Location:</strong> ${ticket.eventId.location.name}</p>
                <p><strong>Pass:</strong> ${ticket.passName || 'General'}</p>
                <p><strong>Quantity:</strong> ${ticket.quantity}</p>
                <p><strong>Status:</strong> ${ticket.status}</p>
              </div>
              <div class="footer">
                <p>Present this ticket at the event entrance</p>
                <p>Generated by TICKETr - ai. consultancy</p>
              </div>
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin" />
      </div>
    );
  }

  if (!ticket) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Ticket not found</h1>
          <Button onClick={() => router.push('/my-tickets')}>
            Back to My Tickets
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Header />
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <Button
            variant="ghost"
            onClick={() => router.push('/my-tickets')}
            className="mb-4"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to My Tickets
          </Button>
          <h1 className="text-3xl font-bold text-gray-900">Your Ticket</h1>
        </div>

        {/* Ticket Card */}
        <Card className="overflow-hidden">
          <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white p-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-bold mb-2">TICKETr</h2>
                <p className="text-blue-100">ai. consultancy</p>
              </div>
              <Badge className="bg-white/20 text-white border-white/30">
                {ticket.status.charAt(0).toUpperCase() + ticket.status.slice(1)}
              </Badge>
            </div>
          </div>

          <CardContent className="p-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              {/* Event Details */}
              <div className="space-y-6">
                <div>
                  <h3 className="text-xl font-semibold mb-4">{ticket.eventId.name}</h3>
                  
                  <div className="space-y-3">
                    <div className="flex items-center space-x-3">
                      <Calendar className="w-5 h-5 text-gray-500" />
                      <span>{formatDate(ticket.eventId.date)}</span>
                    </div>
                    <div className="flex items-center space-x-3">
                      <Clock className="w-5 h-5 text-gray-500" />
                      <span>{ticket.eventId.time}</span>
                    </div>
                    <div className="flex items-center space-x-3">
                      <MapPin className="w-5 h-5 text-gray-500" />
                      <div>
                        <p className="font-medium">{ticket.eventId.location.name}</p>
                        <p className="text-sm text-gray-600">{ticket.eventId.location.address}</p>
                      </div>
                    </div>
                  </div>
                </div>

                <Separator />

                <div>
                  <h4 className="font-semibold mb-3">Ticket Information</h4>
                  <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span className="text-gray-600">Ticket ID:</span>
                      <span className="font-mono text-xs">{ticket.ticketId}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">Pass Type:</span>
                      <span>{ticket.passName || 'General'}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">Quantity:</span>
                      <span>{ticket.quantity}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">Total Amount:</span>
                      <span className="font-medium">{formatPrice(ticket.totalAmount)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">Purchase Date:</span>
                      <span>{formatDate(ticket.createdAt)}</span>
                    </div>
                    {ticket.scannedAt && (
                      <div className="flex justify-between">
                        <span className="text-gray-600">Scanned At:</span>
                        <span>{formatDate(ticket.scannedAt)}</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* QR Code */}
              <div className="space-y-6">
                <div className="text-center">
                  <h4 className="font-semibold mb-4">QR Code</h4>
                  <div className="bg-white p-6 rounded-lg border-2 border-dashed border-gray-300">
                    {qrCodeUrl ? (
                      <img
                        src={qrCodeUrl}
                        alt="QR Code"
                        className="mx-auto"
                        width={200}
                        height={200}
                      />
                    ) : (
                      <div className="w-48 h-48 bg-gray-100 rounded-lg flex items-center justify-center">
                        <Loader2 className="w-8 h-8 animate-spin text-gray-400" />
                      </div>
                    )}
                  </div>
                  <p className="text-sm text-gray-600 mt-4">
                    Show this QR code at the event entrance
                  </p>
                </div>

                <div className="space-y-3">
                  <Button onClick={handleDownload} className="w-full">
                    <Download className="w-4 h-4 mr-2" />
                    Download Ticket
                  </Button>
                  
                  <Button
                    variant="outline"
                    onClick={() => window.print()}
                    className="w-full"
                  >
                    Print Ticket
                  </Button>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Event Image */}
        <Card className="mt-6">
          <div className="relative h-64 w-full">
            <Image
              src={ticket.eventId.image}
              alt={ticket.eventId.name}
              fill
              className="object-cover rounded-lg"
            />
          </div>
        </Card>
      </div>
    </div>
  );
}
